(in-package #:strahbroker)

(defun menu ()
  '((:link "/" :title "Главная")
    (:link "/about" :title "Страхование")
        (:link "/clients" :title "Клиенты")
        (:link "/biografy" :title "Биография-страхового-брокера")
        (:link "/whoyz" :title "Яков Зайдман")
        (:link "/strahbr" :title "Кто-такой-страховой-брокер")
        (:link "/strahkons" :title "Кто-такой-страховой-консультант")
        (:link "/work" :title "Проекты")
    (:link "/article" :title "Статьи")
    (:link "/service" :title "Услуги")
        (:link "/kasko" :title "КАСКО")
        (:link "/osago" :title "ОСАГО")
        (:link "/regulations" :title "Правила-страхования")
    (:link "/apparat" :title "Аппарат")
    (:link "/contacts" :title "Контакты")))

;; start
(restas:start '#:strahbroker :port )
(restas:debug-mode-on)
;; (restas:debug-mode-off)
(setf hunchentoot:*catch-errors-p* t)
